// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8k_l8a3YRhJQv1prfcsDMRSxIIZRqbu4',
    appId: '1:1043894238865:android:9b93fc1dd4ff5567d5c930',
    messagingSenderId: '1043894238865',
    projectId: 'attendify-lalitjindal-a6e9e',
    storageBucket: 'attendify-lalitjindal-a6e9e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfAsbP_xuJdZyqn7W35YuzR8FuU1rPLrQ',
    appId: '1:1043894238865:ios:f58ee0c3f8ba1cd2d5c930',
    messagingSenderId: '1043894238865',
    projectId: 'attendify-lalitjindal-a6e9e',
    storageBucket: 'attendify-lalitjindal-a6e9e.firebasestorage.app',
    iosClientId: '1043894238865-k0e8o3sjsk7vahuj2ogikapasfds0f73.apps.googleusercontent.com',
    iosBundleId: 'com.lalitjindal.attendance',
  );
}
