import 'package:flutter/material.dart';

/// Seed color and generated [ColorScheme]s for Attendify — Meridian design language.
///
/// Primary seed: Deep Indigo (#4B39EF).
/// Provides [light], [dark], and [amoled] color schemes.
/// Semantic tokens (success, warning, semantic attendance colors) are defined
/// as static constants below and referenced throughout the app.
abstract final class AppColorScheme {
  AppColorScheme._();

  // ── Brand Seed ──────────────────────────────────────────────────────────────

  /// Primary brand seed — Deep Indigo.
  static const Color seedColor = Color(0xFF4B39EF);

  // ── Generated Schemes ────────────────────────────────────────────────────────

  /// Light theme [ColorScheme].
  static final ColorScheme light = ColorScheme.fromSeed(
    seedColor: seedColor,
    brightness: Brightness.light,
    // Override specific semantic roles for Meridian precision
    primary: const Color(0xFF4B39EF),
    onPrimary: Colors.white,
    primaryContainer: const Color(0xFFE0DEFF),
    onPrimaryContainer: const Color(0xFF13008E),
    secondary: const Color(0xFFF59E0B),
    onSecondary: Colors.white,
    secondaryContainer: const Color(0xFFFEF3C7),
    onSecondaryContainer: const Color(0xFF78350F),
    tertiary: const Color(0xFFEF4444),
    onTertiary: Colors.white,
    tertiaryContainer: const Color(0xFFFEE2E2),
    onTertiaryContainer: const Color(0xFF7F1D1D),
    error: const Color(0xFFEF4444),
    onError: Colors.white,
    surface: Colors.white,
    onSurface: const Color(0xFF1A1A2E),
    onSurfaceVariant: const Color(0xFF5C5A7A),
    surfaceContainerLowest: Colors.white,
    surfaceContainerLow: const Color(0xFFF8F7FF),
    surfaceContainer: const Color(0xFFF1F0FF),
    surfaceContainerHigh: const Color(0xFFE8E7FF),
    surfaceContainerHighest: const Color(0xFFDDD9FF),
    outline: const Color(0xFFC4C2E0),
    outlineVariant: const Color(0xFFE8E7F5),
  );

  /// Dark theme [ColorScheme].
  static final ColorScheme dark = ColorScheme.fromSeed(
    seedColor: seedColor,
    brightness: Brightness.dark,
    primary: const Color(0xFF8B83FF),
    onPrimary: const Color(0xFF220077),
    primaryContainer: const Color(0xFF3300A8),
    onPrimaryContainer: const Color(0xFFE0DEFF),
    secondary: const Color(0xFFFCD34D),
    onSecondary: const Color(0xFF78350F),
    secondaryContainer: const Color(0xFF92400E),
    onSecondaryContainer: const Color(0xFFFEF3C7),
    tertiary: const Color(0xFFF87171),
    onTertiary: const Color(0xFF7F1D1D),
    tertiaryContainer: const Color(0xFF991B1B),
    onTertiaryContainer: const Color(0xFFFEE2E2),
    error: const Color(0xFFF87171),
    onError: const Color(0xFF7F1D1D),
    surface: const Color(0xFF1A1828),
    onSurface: const Color(0xFFE8E6FF),
    onSurfaceVariant: const Color(0xFFA9A6CC),
    surfaceContainerLowest: const Color(0xFF0C0B14),
    surfaceContainerLow: const Color(0xFF161524),
    surfaceContainer: const Color(0xFF1E1C2D),
    surfaceContainerHigh: const Color(0xFF262438),
    surfaceContainerHighest: const Color(0xFF2E2C42),
    outline: const Color(0xFF6E6B8A),
    outlineVariant: const Color(0xFF3A3850),
  );

  /// AMOLED / true-black dark theme [ColorScheme].
  /// On AMOLED displays, pure-black pixels are off — saving battery.
  static final ColorScheme amoled = dark.copyWith(
    surface: const Color(0xFF000000),
    surfaceContainerLowest: const Color(0xFF000000),
    surfaceContainerLow: const Color(0xFF080811),
    surfaceContainer: const Color(0xFF0E0E1E),
    surfaceContainerHigh: const Color(0xFF151526),
    surfaceContainerHighest: const Color(0xFF1C1C30),
    onSurface: const Color(0xFFF0EEFF),
  );

  // ── Semantic / Custom Color Overrides ────────────────────────────────────────
  // These are NOT generated by M3's seed algorithm. They are curated tokens
  // that override M3 defaults for semantic accuracy in attendance/task context.

  /// ✓ Present — Emerald green.
  static const Color success = Color(0xFF10B981);
  static const Color successContainer = Color(0xFFD1FAE5);
  static const Color onSuccessContainer = Color(0xFF064E3B);
  static const Color successDark = Color(0xFF34D399);

  /// ⚠ Warning / Due soon — Amber.
  static const Color warning = Color(0xFFF59E0B);
  static const Color warningContainer = Color(0xFFFEF3C7);
  static const Color warningDark = Color(0xFFFCD34D);

  /// ✗ Danger / Overdue / Absent — Rose red.
  static const Color danger = Color(0xFFEF4444);
  static const Color dangerContainer = Color(0xFFFEE2E2);
  static const Color dangerDark = Color(0xFFF87171);

  // ── Task Priority Colors ─────────────────────────────────────────────────────
  static const Color taskCritical = Color(0xFFEF4444);
  static const Color taskHigh = Color(0xFFF97316);
  static const Color taskMedium = Color(0xFF3B82F6);
  static const Color taskLow = Color(0xFF10B981);

  // ── Subject Accent Colors (8-color cycle) ────────────────────────────────────
  static const List<Color> subjectColors = [
    Color(0xFF6366F1), // Indigo
    Color(0xFF8B5CF6), // Violet
    Color(0xFFEC4899), // Pink
    Color(0xFFF59E0B), // Amber
    Color(0xFF10B981), // Emerald
    Color(0xFF3B82F6), // Blue
    Color(0xFF14B8A6), // Teal
    Color(0xFFF97316), // Orange
  ];
}
